import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, BrainCircuit, Check, ExternalLink, Minus, Radio, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { useTradeReceipt, type TradeReceipt } from './hooks/useTradeReceipt';
import { PerformancePanel } from './PerformancePanel';
import './logo.css';

const explorer = (hash?: string | null) => hash ? `https://shannon-explorer.somnia.network/tx/${hash}` : '#';
const addressExplorer = (value?: string | null) => value ? `https://shannon-explorer.somnia.network/address/${value}` : '#';
const short = (hash?: string | null) => hash ? `${hash.slice(0, 7)}…${hash.slice(-5)}` : '—';
const money = (value?: number | null) => value == null ? '—' : `$${value.toLocaleString('en-US', { maximumFractionDigits: 2 })}`;

function useAnimatedNumber(target: number, duration = 850) {
  const [value, setValue] = useState(target); const previous = useRef(target);
  useEffect(() => { const from = previous.current; previous.current = target; const started = performance.now(); let frame = 0; const tick = (now: number) => { const p = Math.min(1, (now - started) / duration); setValue(from + (target - from) * (1 - Math.pow(1 - p, 3))); if (p < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [target, duration]);
  return value;
}

function ParticleField() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = ref.current!; const ctx = canvas.getContext('2d')!; let raf = 0; const dots = Array.from({ length: 72 }, (_, i) => ({ x: Math.random(), y: Math.random(), r: .4 + Math.random() * 1.2, a: .12 + Math.random() * .5, v: .00003 + Math.random() * .00008, p: i })); const resize = () => { canvas.width = innerWidth * devicePixelRatio; canvas.height = innerHeight * devicePixelRatio; canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); }; resize(); addEventListener('resize', resize); const draw = (t: number) => { ctx.clearRect(0, 0, innerWidth, innerHeight); for (const d of dots) { const x = d.x * innerWidth + Math.sin(t * d.v + d.p) * 18; const y = (d.y * innerHeight + t * d.v * 15) % innerHeight; ctx.beginPath(); ctx.fillStyle = `rgba(0,217,255,${d.a})`; ctx.arc(x, y, d.r, 0, Math.PI * 2); ctx.fill(); } raf = requestAnimationFrame(draw); }; raf = requestAnimationFrame(draw); return () => { cancelAnimationFrame(raf); removeEventListener('resize', resize); }; }, []);
  return <canvas className="particle-field" ref={ref} aria-hidden="true" />;
}

function Typewriter({ text }: { text: string }) { const [shown, setShown] = useState(''); useEffect(() => { setShown(''); let i = 0; const timer = setInterval(() => { i++; setShown(text.slice(0, i)); if (i >= text.length) clearInterval(timer); }, 22); return () => clearInterval(timer); }, [text]); return <span>{shown}<i className="cursor" /></span>; }

function Orb({ receipt, thinking, asset }: { receipt: TradeReceipt; thinking: boolean; asset:'BTC'|'ETH' }) {
  const decision = receipt.llmDecision?.decision ?? 'NEUTRAL'; const mode = decision === 'UP' ? 'up' : decision === 'DOWN' ? 'down' : 'neutral'; const source=asset==='ETH'?receipt.priceSignal?.eth:receipt.priceSignal?.current;const price = useAnimatedNumber(source?.usd ?? 0); const first = asset==='BTC'?(receipt.priceSignal?.first.usd ?? price):price; const delta = asset==='BTC'?(receipt.priceSignal?.changePct ?? 0):0; const selected = receipt.riskGate;const measured=selected?.secondsLeft??receipt.discovery?.candidates.find(c=>c.asset===asset&&c.isTradable)?.secondsLeft??0;const snapshotSeconds=receipt.finishedAt?0:selected?.expiry?Math.max(0,selected.expiry-Math.floor(Date.now()/1000)):measured;const[s, setS]=useState(snapshotSeconds);useEffect(()=>{setS(snapshotSeconds);const timer=setInterval(()=>setS(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[snapshotSeconds,receipt.cycleId]);const seconds=Math.max(0,s); const maxWindow = selected?.windowSeconds&&selected.windowSeconds>0?selected.windowSeconds:Math.max(seconds,1); const circumference = 2 * Math.PI * 147; const dash = circumference * Math.min(1, seconds / maxWindow);const[burst,setBurst]=useState(false);const seen=useRef<string|undefined>(undefined);useEffect(()=>{const id=receipt.order?.status==='confirmed'?(receipt.order.txHash??receipt.order.orderId):undefined;if(id&&id!==seen.current){seen.current=id;setBurst(true);const t=setTimeout(()=>setBurst(false),1800);return()=>clearTimeout(t)}},[receipt.order?.status,receipt.order?.txHash,receipt.order?.orderId]);
  return <section className={`reactor reactor--${mode} ${thinking ? 'is-thinking' : ''} ${burst ? 'is-filled' : ''}`}>
    <div className="orb-caption orb-caption--price"><span>{asset} / USD</span><strong>{source?money(price):'SYNC PENDING'}</strong><small>{asset==='BTC'&&source?`PREV ${money(first)}`:asset==='ETH'?'NEXT CYCLE FEED':'AWAITING AGENT'}</small></div>
    <div className="orb-caption orb-caption--trend"><span>VECTOR</span><strong>{delta>0?<ArrowUpRight/>:delta<0?<ArrowDownRight/>:<Minus/>}{asset==='BTC'?(receipt.priceSignal?.trend??'SYNC'):'SPOT'}</strong><small>{asset==='BTC'&&receipt.priceSignal?`${delta.toFixed(4)}%`:'CURRENT SAMPLE'}</small></div>
    <div className="orb-caption orb-caption--market"><span>MARKET WINDOW</span><strong>{seconds || '—'}<em>S</em></strong><small>{selected?.marketId ? <a href={`https://shannon-explorer.somnia.network/search?q=${selected.marketId}`} target="_blank">#{selected.marketId.slice(-6)}</a> : 'SCANNING'}</small></div>
    <svg className="expiry-ring" viewBox="0 0 340 340"><circle cx="170" cy="170" r="147"/><circle className="expiry-progress" cx="170" cy="170" r="147" style={{ strokeDasharray: `${dash} ${circumference}` }}/></svg>
    <div className="ring ring--outer"><span/><span/><span/><span/></div><div className="ring ring--mid"><span/><span/><span/></div><div className="ring ring--inner"/>
    <div className="orb-glow"/><div className="orb-core"><div className="orb-grid"/><div className="orb-light"/><div className="orb-seam"/><div className="orb-status"><BrainCircuit/><small>ORACLE CORE</small><strong>{thinking ? 'THINKING' : decision}</strong></div></div><div className="energy-beam energy-beam--left"/><div className="energy-beam energy-beam--right"/><div className="burst"/>
  </section>;
}

function CornerPanel({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`hud-panel ${className}`}><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/>{children}</div>; }

function Timeline({ receipt }: { receipt: TradeReceipt }) {
  const stages = [
    { icon: Radio, code: '01', label: 'PRICE SIGNAL', state: receipt.priceSignal ? 'COMPLETE' : 'WAITING', body: receipt.priceSignal ? <><b><a href={explorer(receipt.priceSignal.first.txHash)} target="_blank">{money(receipt.priceSignal.first.usd)}</a></b><span className="flow-arrow">→</span><b><a href={explorer(receipt.priceSignal.current.txHash)} target="_blank">{money(receipt.priceSignal.current.usd)}</a></b><small>{receipt.priceSignal.trend} · {receipt.priceSignal.changePct.toFixed(4)}% · TX PROOFS ↗</small></> : <small className="empty-state">AWAITING JSON AGENT CALLBACK</small> },
    { icon: BrainCircuit, code: '02', label: 'LLM INFERENCE', state: receipt.llmDecision?.decision ?? 'WAITING', body: <><b className={`decision decision--${receipt.llmDecision?.decision?.toLowerCase()}`}>{receipt.llmDecision?.decision ?? '—'}</b><p><Typewriter text={receipt.llmDecision?.reasoning ?? 'Awaiting cognitive response…'} /></p>{receipt.llmDecision&&<small><a href={explorer(receipt.llmDecision.txHash)} target="_blank">LLM PROOF {short(receipt.llmDecision.txHash)} ↗</a></small>}</> },
    { icon: ShieldCheck, code: '03', label: 'RISK GATE', state: receipt.riskGate ? receipt.riskGate.allowed ? 'PASSED' : 'DENIED' : 'WAITING', body: <><b>{receipt.riskGate?.allowed ? 'AUTHORIZED' : receipt.riskGate ? 'INTERCEPTED' : '—'}</b><p>{receipt.riskGate?.reason ?? 'Deterministic policy standby'}</p></> },
    { icon: Zap, code: '04', label: 'EXECUTION', state: receipt.order?.status?.toUpperCase() ?? 'WAITING', body: <><b>{receipt.order?.status === 'confirmed' ? `${receipt.order.filledShares ?? 0} SHARES FILLED` : receipt.order?.status?.toUpperCase() ?? '—'}</b><p>{receipt.order?.txHash ? <a href={explorer(receipt.order.txHash)} target="_blank">{short(receipt.order.txHash)} <ExternalLink size={11}/></a> : receipt.order?.reason ?? 'dreamDEX order rail ready'}</p></> },
  ];
  return <div className="timeline">{stages.map(({ icon: Icon, ...s }, index) => <CornerPanel key={s.code} className={`timeline-card ${['PASSED','COMPLETE','CONFIRMED'].includes(s.state) ? 'is-good' : ''}`}><header><span className="stage-code">{s.code}</span><Icon/><div><small>{s.label}</small><strong>{s.state}</strong></div>{index < stages.length - 1 && <i className="stage-line"/>}</header><div className="stage-body">{s.body}</div></CornerPanel>)}</div>;
}

export default function App() {
  const { receipt:liveReceipt,history,loading,stale,error,refreshedAt }=useTradeReceipt();const[selectedCycle,setSelectedCycle]=useState<string|null>(null);const[asset,setAsset]=useState<'BTC'|'ETH'>('BTC');const receipt=selectedCycle?history.find(x=>x.cycleId===selectedCycle)??liveReceipt:liveReceipt;const stage=receipt.currentStage??(receipt.finishedAt?'complete':'initializing');const active=!['complete','error'].includes(stage)&&!receipt.finishedAt;const stageLabels:Record<string,string>={initializing:'INITIALIZING',price_sample_1:'FETCHING BTC',trend_sampling:'SAMPLING TREND',price_sample_2:'FETCHING BTC',eth_price:'FETCHING ETH',llm_inference:'CONSULTING LLM',discovery:'DISCOVERING MARKET',risk_gate:'CHECKING RISK',order_execution:'PLACING ORDER'};const thinking=loading||active;const status=error?'LINK ERROR':active?(stageLabels[stage]??'AGENT THINKING'):receipt.error?'CYCLE HALTED':receipt.order?.status==='confirmed'?'ORDER FILLED':receipt.order?.status==='skipped'?'CYCLE SKIPPED':'SYSTEM ONLINE';const market=receipt.riskGate;
  const metrics = useMemo(() => [['CHAIN',String(receipt.network?.chainId??'—'),receipt.network?.name??(receipt.network?.chainId===50312?'SOMNIA TESTNET':'UNKNOWN NETWORK')],['REQUEST',receipt.llmDecision?.requestId ?? receipt.priceSignal?.current.requestId ?? '—','AGENT CONSENSUS'],['LIQUIDITY',market ? `${market.liquidityShares.toLocaleString()} SH` : '—','MATCHING RANGE'],['EXPOSURE',market ? `${market.maxCostTUSDC.toFixed(4)} tUSDC` : '—','HARD CAPPED']], [receipt, market]);
  return <div className="app"><ParticleField/><div className="scanlines"/><header className="topbar"><div className="brand"><img className="brand-logo" src="/oracle-arena-logo.png" alt="" aria-hidden="true"/><div><h1>ORACLE <b>ARENA</b></h1><p>AUTONOMOUS MARKET INTELLIGENCE</p></div></div><div className="system-strip"><span className={`signal ${error ? 'bad' : ''}`}/><div><small>CORE STATUS</small><strong>{status}</strong></div><i/><div><small>DATA LINK</small><strong>{stale ? 'STALE' : 'SYNCHRONIZED'}</strong></div><i/><div className="clock"><small>LAST TELEMETRY</small><strong>{refreshedAt ? refreshedAt.toLocaleTimeString([], { hour12: false }) : '—'}</strong></div></div></header>
    <main><div className="asset-toggle"><button className={asset==='BTC'?'active':''} onClick={()=>setAsset('BTC')}>BTC</button><button className={asset==='ETH'?'active':''} onClick={()=>setAsset('ETH')}>ETH</button></div><section className="hero"><div className="side-readout side-readout--left"><p>NEURAL PROCESS</p><b>{receipt.cycleId?.slice(0,8).toUpperCase() ?? 'STANDBY'}</b><span/><small>{stageLabels[stage]??(receipt.startedAt?new Date(receipt.startedAt).toLocaleString():'Awaiting cycle')}</small></div><Orb receipt={receipt} thinking={thinking} asset={asset}/><div className="mobile-telemetry"><div><small>SPOT</small><strong>{money(asset==='ETH'?receipt.priceSignal?.eth?.usd:receipt.priceSignal?.current.usd)}</strong></div><div><small>VECTOR</small><strong className={'decision--'+receipt.llmDecision?.decision?.toLowerCase()}>{asset==='BTC'?(receipt.priceSignal?.trend??'SYNC'):'SPOT'}</strong></div><div><small>WINDOW</small><strong>{market?.secondsLeft!=null?market.secondsLeft+'s':'—'}</strong></div></div><div className="side-readout side-readout--right"><p>DECISION MATRIX</p><b>{receipt.llmDecision?.confidence?.toUpperCase() ?? 'UNRATED'}</b><span/><small>CONFIDENCE BAND</small></div></section>
      <section className="metrics">{metrics.map(([label,value,note]) => <div key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>)}</section>
      <section className="receipt-section"><div className="section-title"><div><Sparkles/><span>MISSION TELEMETRY</span></div><h2>TRADE RECEIPT <em>/ LIVE PIPELINE</em></h2><p>{receipt.finishedAt ? `CYCLE SEALED ${new Date(receipt.finishedAt).toLocaleTimeString([], { hour12: false })}` : 'LISTENING FOR ON-CHAIN EVENTS'}</p></div><Timeline receipt={receipt}/></section>
      <section className="lower-deck"><CornerPanel className="market-panel"><header><Activity/><div><small>ACTIVE MARKET</small><strong>{market?.marketId ? <a href={`https://shannon-explorer.somnia.network/search?q=${market.marketId}`} target="_blank">BTC EVENT / {market.marketId.slice(-6).toUpperCase()} ↗</a> : 'NO MARKET LOCK'}</strong></div></header><div className="market-grid"><div><small>POOL</small><b>{market?.pool?<a href={addressExplorer(market.pool)} target="_blank">{short(market.pool)} ↗</a>:'—'}</b></div><div><small>OUTCOME</small><b>{market?.outcome ?? '—'}</b></div><div><small>BEST ASK</small><b>{market?.bestAsk?.toFixed(3) ?? '—'}</b></div><div><small>LIMIT</small><b>{market?.limitPrice?.toFixed(3) ?? '—'}</b></div></div></CornerPanel><CornerPanel className="proof-panel"><Check/><div><small>VERIFIABLE AUTONOMY</small><strong>ON-CHAIN PROOF MATRIX</strong><p className="proof-links"><a href={`https://shannon-explorer.somnia.network/search?q=${receipt.agents?.jsonApiAgentId??'13174292974160097713'}`} target="_blank">JSON AGENT · {receipt.agents?.jsonApiAgentId??'13174292974160097713'} ↗</a><a href={`https://shannon-explorer.somnia.network/search?q=${receipt.agents?.llmInferenceAgentId??'12847293847561029384'}`} target="_blank">LLM AGENT · {receipt.agents?.llmInferenceAgentId??'12847293847561029384'} ↗</a><a href={addressExplorer(receipt.agents?.callbackAddress??'0x4c88a0b56E8AdBe91328fac6F9ddD1C5619B84Df')} target="_blank">CALLBACK · {short(receipt.agents?.callbackAddress??'0x4c88a0b56E8AdBe91328fac6F9ddD1C5619B84Df')} ↗</a></p></div></CornerPanel></section>
      <PerformancePanel history={history}/>
      <section className="history-section"><div className="section-title"><div><Activity/><span>CYCLE ARCHIVE</span></div><h2>RECENT MISSIONS <em>/ LAST 20</em></h2></div><div className="history-strip"><button className={!selectedCycle?'active':''} onClick={()=>setSelectedCycle(null)}>LIVE</button>{history.map(h=><button key={h.cycleId} className={selectedCycle===h.cycleId?'active':''} onClick={()=>setSelectedCycle(h.cycleId??null)}><small>{h.finishedAt?new Date(h.finishedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'RUNNING'}</small><b className={`decision--${h.llmDecision?.decision?.toLowerCase()}`}>{h.llmDecision?.decision??'—'}</b><span>{h.order?.status==='confirmed'?'FILLED':h.order?.status==='skipped'?'SKIP':h.error?'ERROR':'OPEN'}</span></button>)}</div></section>
    </main><footer><span>OA // OBSERVATORY NODE 01</span><span>TESTNET TELEMETRY · AUTONOMOUS EXECUTION</span><span>{error ?? 'ENCRYPTED UPLINK ACTIVE'}</span></footer></div>;
}
