import {createPublicClient,createWalletClient,defineChain,http,parseAbi} from 'viem';import {privateKeyToAccount} from 'viem/accounts';
const moduleAbi=parseAbi(['function markets(bytes32) view returns(uint256,uint8,uint8,address,uint32,bytes32,address,address,address,address,uint256,uint256,uint64,uint64)','function redeem(uint32,bytes32,bytes32,uint8,uint256)']);
const marketAbi=parseAbi(['function isResolved() view returns(bool)','function isVoided() view returns(bool)','function payoutNumerators() view returns(uint256[])','function outcomeToken() view returns(address)']);
const tokenAbi=parseAbi(['function balanceOf(address,uint256) view returns(uint256)','function isOperator(address,address) view returns(bool)','function setOperator(address,bool)']);
const erc20Abi=parseAbi(['function balanceOf(address) view returns(uint256)','function decimals() view returns(uint8)']);
const zero32=`0x${'0'.repeat(64)}`,zeroAddress=`0x${'0'.repeat(40)}`;export const redeemKey=(marketId,outcome,wallet)=>`${marketId.toLowerCase()}:${outcome}:${wallet.toLowerCase()}`;const err=e=>e instanceof Error?e.message.slice(0,300):String(e).slice(0,300);
const sameAddress=(a,b)=>String(a).toLowerCase()===String(b).toLowerCase();
export async function redeemHistory(history,deps,{dryRun=true}={}){const seen=new Set(),out=[];
  for(const entry of history){const marketId=entry?.marketContext?.marketId??entry?.riskGate?.marketId,outcome=entry?.riskGate?.outcome??(entry?.llmDecision?.decision==='UP'?'YES':entry?.llmDecision?.decision==='DOWN'?'NO':null),filled=entry?.order?.filledShares??0;
    if(!marketId||!outcome||!(filled>0)){out.push({...entry,redeem:entry.redeem??{status:'not_eligible',checkedAt:new Date().toISOString(),reason:'requires a real non-zero fill'}});continue}
    const key=redeemKey(marketId,outcome,deps.walletAddress);if(seen.has(key)||['confirmed','already_redeemed'].includes(entry?.redeem?.status)){seen.add(key);out.push(entry);continue}seen.add(key);
    try{
      if(entry?.redeem?.status==='submitted'){if(!entry.redeem.txHash||!deps.getReceipt){out.push(entry);continue}const prior=await deps.getReceipt(entry.redeem.txHash);if(!prior){out.push(entry);continue}if(prior.status==='success'){out.push({...entry,redeem:{...entry.redeem,status:'confirmed',confirmedAt:new Date().toISOString(),amountReceived:entry.redeem.amountReceived??null}});continue}}
      let state=await deps.readState({marketId,outcome,wallet:deps.walletAddress,filledShares:filled,expectedPool:entry?.riskGate?.pool});
      if(!state.settled){out.push({...entry,redeem:{status:'not_eligible',checkedAt:new Date().toISOString(),idempotencyKey:key,reason:'market is not resolved/voided and redeemable'}});continue}
      if(!(state.balanceRaw>0n)){out.push({...entry,redeem:{status:'not_eligible',checkedAt:new Date().toISOString(),idempotencyKey:key,amountClaimable:0,reason:'no outcome-token balance; prior redemption cannot be proven without a confirmed receipt'}});continue}
      if(!(state.payoutNumerator>0n)){out.push({...entry,redeem:{status:'not_eligible',checkedAt:new Date().toISOString(),idempotencyKey:key,amountClaimable:0,reason:'held outcome has zero payout'}});continue}
      const amountRaw=state.balanceRaw<state.filledRaw?state.balanceRaw:state.filledRaw,claimRaw=amountRaw*state.payoutNumerator/state.payoutDenominator,eligible={status:'eligible',checkedAt:new Date().toISOString(),idempotencyKey:key,amountClaimable:Number(claimRaw)/10**state.decimals,amountReceived:null,txHash:null,dryRun};
      if(dryRun){out.push({...entry,redeem:eligible});continue}
      const priorIdentity=state;state=await deps.readState({marketId,outcome,wallet:deps.walletAddress,filledShares:filled,expectedPool:entry?.riskGate?.pool});
      if(!state.settled||state.balanceRaw<amountRaw||state.payoutNumerator===0n||!sameAddress(state.pool,priorIdentity.pool)||!sameAddress(state.outcomeToken,priorIdentity.outcomeToken)||state.outcomeId!==priorIdentity.outcomeId)throw Error('redeem pre-write state or market identity changed');
      const onSubmitted=async hash=>{const submitted={...eligible,status:'submitted',submittedAt:new Date().toISOString(),txHash:hash,dryRun:false};if(deps.persistSubmitted)await deps.persistSubmitted(entry,submitted)};
      const result=await deps.writeRedeem({marketId,outcomeIdx:outcome==='YES'?0:1,amountRaw,state,onSubmitted});const redeem={...eligible,status:result.status==='success'?'confirmed':'reverted',submittedAt:result.submittedAt??new Date().toISOString(),confirmedAt:new Date().toISOString(),txHash:result.hash??null,amountReceived:result.status==='success'?result.amountReceived:null,error:result.status==='success'?undefined:(result.error??'redeem transaction reverted'),dryRun:false};out.push({...entry,redeem});
    }catch(error){out.push({...entry,redeem:{status:'reverted',checkedAt:new Date().toISOString(),idempotencyKey:key,error:err(error),dryRun:false}})}
  }return out;
}
export function createRedeemDeps({rpc,moduleAddress,privateKey}){const chain=defineChain({id:50312,name:'Somnia Testnet',nativeCurrency:{name:'STT',symbol:'STT',decimals:18},rpcUrls:{default:{http:[rpc]}}}),account=privateKeyToAccount(privateKey),client=createPublicClient({batch:{multicall:false},chain,transport:http(rpc)}),wallet=createWalletClient({account,chain,transport:http(rpc)});
  return{walletAddress:account.address,getReceipt:async hash=>client.getTransactionReceipt({hash}).catch(()=>null),async readState({marketId,outcome,filledShares,expectedPool}){const rec=await client.readContract({address:moduleAddress,abi:moduleAbi,functionName:'markets',args:[marketId]}),collateral=rec[3],market=rec[8],pool=rec[9],outcomeId=outcome==='YES'?rec[10]:rec[11];if(sameAddress(market,zeroAddress)||sameAddress(pool,zeroAddress))throw Error('unknown market or pool');if(expectedPool&&!sameAddress(pool,expectedPool))throw Error('market pool does not match the recorded execution pool');const outcomeToken=await client.readContract({address:market,abi:marketAbi,functionName:'outcomeToken'});const[resolved,voided,payouts,balanceRaw,decimals]=await Promise.all([client.readContract({address:market,abi:marketAbi,functionName:'isResolved'}),client.readContract({address:market,abi:marketAbi,functionName:'isVoided'}),client.readContract({address:market,abi:marketAbi,functionName:'payoutNumerators'}),client.readContract({address:outcomeToken,abi:tokenAbi,functionName:'balanceOf',args:[account.address,outcomeId]}),client.readContract({address:collateral,abi:erc20Abi,functionName:'decimals'}).catch(()=>6)]);const idx=outcome==='YES'?0:1,den=payouts.reduce((n,x)=>n+x,0n);return{settled:resolved||voided,balanceRaw,payoutNumerator:payouts[idx]??0n,payoutDenominator:den||10_000_000n,filledRaw:BigInt(Math.floor(filledShares*10**Number(decimals))),decimals:Number(decimals),outcomeToken,outcomeId,collateral,pool};},async writeRedeem({marketId,outcomeIdx,amountRaw,state,onSubmitted}){const approved=await client.readContract({address:state.outcomeToken,abi:tokenAbi,functionName:'isOperator',args:[account.address,moduleAddress]});if(!approved){const approvalHash=await wallet.writeContract({address:state.outcomeToken,abi:tokenAbi,functionName:'setOperator',args:[moduleAddress,true]});const approvalReceipt=await client.waitForTransactionReceipt({hash:approvalHash});if(approvalReceipt.status!=='success')return{status:'reverted',hash:approvalHash,error:'operator approval reverted'}}const before=await client.readContract({address:state.collateral,abi:erc20Abi,functionName:'balanceOf',args:[account.address]});let hash=await wallet.writeContract({address:moduleAddress,abi:moduleAbi,functionName:'redeem',args:[0,zero32,marketId,outcomeIdx,amountRaw]});await onSubmitted(hash);const receipt=await client.waitForTransactionReceipt({hash,onReplaced:async replacement=>{hash=replacement.transaction.hash;await onSubmitted(hash)}});if(receipt.status!=='success')return{status:'reverted',hash};const after=await client.readContract({address:state.collateral,abi:erc20Abi,functionName:'balanceOf',args:[account.address]});return{status:'success',hash,amountReceived:Number(after-before)/10**state.decimals}}};}
