import test from 'node:test';import assert from 'node:assert/strict';import {evidenceFor,performanceFor,sanitize} from './_views.mjs';
test('evidence is versioned, hashed and sanitized',()=>{const e=evidenceFor({cycleId:'c1',privateKey:'bad',llmDecision:{raw:'{}'}});assert.equal(e.schemaVersion,'oracle-arena-evidence/1.0');assert.ok(e.integrity.bundleHash);assert.equal(JSON.stringify(e).includes('bad'),false)});
test('performance counts fills and leaves unavailable payout unknown',()=>{const p=performanceFor([{order:{status:'confirmed',filledShares:0,price:.5}},{order:{status:'confirmed',filledShares:2,price:.4},settlement:{result:'WIN'}}]);assert.equal(p.filledTrades,1);assert.equal(p.totalPayout,null);assert.equal(p.realizedPnl,null)});
test('partial fill counts once, rested zero fill does not, and reverted is separate',()=>{const p=performanceFor([{order:{status:'confirmed',filledShares:1,submittedSizeShares:2,price:.5,averageFillPrice:.4,rested:true},settlement:{result:'LOSS'}},{order:{status:'confirmed',filledShares:0,rested:true}},{order:{status:'reverted',filledShares:0}}]);assert.equal(p.filledTrades,1);assert.equal(p.revertedTransactions,1);assert.equal(p.totalStake,.4);assert.equal(p.realizedPnl,-.4)});
test('limit price is not substituted for missing actual fill price',()=>{const p=performanceFor([{order:{status:'confirmed',filledShares:1,price:.5},settlement:{result:'LOSS'}}]);assert.equal(p.totalStake,null);assert.equal(p.realizedPnl,null)});
test('legacy history without new fields remains readable',()=>assert.equal(performanceFor([{order:{status:'skipped'}}]).skippedCycles,1));
test('empty history returns finite zero rates and zero financial totals',()=>{const p=performanceFor([]);assert.equal(p.totalCycles,0);assert.equal(p.fillRate,0);assert.equal(p.totalStake,0);assert.equal(p.totalPayout,0);assert.equal(p.realizedPnl,0)});
test('sanitize strips nested secret keys',()=>assert.deepEqual(sanitize({ok:1,nested:{token:'x'}}),{ok:1,nested:{}}));
test('hash is canonical and changes with content while string secrets are redacted',()=>{const a=evidenceFor({cycleId:'c',error:{message:'Authorization: Bearer abcdefghijklmnop'}}),b=evidenceFor({error:{message:'Authorization: Bearer abcdefghijklmnop'},cycleId:'c'}),c=evidenceFor({cycleId:'c',error:{message:'different'}});assert.equal(a.integrity.bundleHash,b.integrity.bundleHash);assert.notEqual(a.integrity.bundleHash,c.integrity.bundleHash);assert.equal(JSON.stringify(a).includes('abcdefghijklmnop'),false)});
